rancher:
  address: https://dev-rancher-02.anatinuslabs.com/v3
  username: token-prxxs
  password: cgk6bcwcqb5n5rkdz88f7x9phlsv77s2x47d58pfcckmjp8nmgdd9c
  aws_cred_name: AWS-rancher-dev

docker: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjogewoJCQkiYXV0aCI6ICJaMmwwYkdGaUsyUmxjR3h2ZVMxMGIydGxiaTAyTVRFME9ESTZZMnBTTFUwMU1VeHlWVVYwV1VadmMyOWFjMkU9IgoJCX0KCX0KfQ==
