apiVersion: v1
kind: Service
metadata:
  name: spawnerservice-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8083
  selector:
    name: spawnerservice-deployment