apiVersion: apps/v1
kind: Deployment
metadata:
  name: spawnerservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spawnerservice-deployment
  template:
    metadata:
      labels:
        name: spawnerservice-deployment
    spec:
      containers:
      - name: application
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        command: [ "/go/bin/spawnersvc"]
        args: []
        env:
        - name: ENV
          value: {{ .Values.env }}
        - name: PORT
          value: '{{ .Values.port }}'
        - name: DEBUG_PORT
          value: '{{ .Values.debug_port }}'
        - name: RANCHER_ADDRESS
          value: {{ .Values.rancher.address }}
        - name: RANCHER_USERNAME
          value: {{ .Values.rancher.username }}
        - name: RANCHER_PASSWORD
          value: {{ .Values.rancher.password }}
        - name: RANCHER_AWS_CRED_NAME
          value: {{ .Values.rancher.aws_cred_name }}

        ports:
          - containerPort: {{ .Values.port }} 
      imagePullSecrets:
        - name: dockerconfigjson-gitlab
      serviceAccountName: awskube2iam
